name: AEGIS CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
        python: ["3.11"]
        build_type: ["ci-debug"]   # use underscore (hyphens can be tricky)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Configure (${{ matrix.build_type }})
        run: cmake --preset ${{ matrix.build_type }}

      - name: Build
        run: cmake --build --preset build-${{ matrix.build_type }}

      - name: C++ tests (CTest)
        run: ctest --preset test-${{ matrix.build_type }} -V

      - name: Install pytest
        run: python -m pip install -U pip pytest

      - name: Python tests (pytest)
        env:
          PYTHONPATH: ${{ github.workspace }}/build/${{ matrix.build_type }}/python:${{ github.workspace }}/python
        run: python -m pytest -q python/tests
